//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Contacts.
        /// </summary>
        internal static string AllContactsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllContactsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies have no last name.
        /// </summary>
        internal static string Contacts_Error_CompanyHasNoLastName {
            get {
                return ResourceManager.GetString("Contacts_Error_CompanyHasNoLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address is invalid.
        /// </summary>
        internal static string Contacts_Error_InvalidEmail {
            get {
                return ResourceManager.GetString("Contacts_Error_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is invalid.
        /// </summary>
        internal static string Contacts_Error_InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("Contacts_Error_InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address is missing.
        /// </summary>
        internal static string Contacts_Error_MissingEmail {
            get {
                return ResourceManager.GetString("Contacts_Error_MissingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is missing.
        /// </summary>
        internal static string Contacts_Error_MissingFirstName {
            get {
                return ResourceManager.GetString("Contacts_Error_MissingFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is missing.
        /// </summary>
        internal static string Contacts_Error_MissingLastName {
            get {
                return ResourceManager.GetString("Contacts_Error_MissingLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is missing.
        /// </summary>
        internal static string Contacts_Error_MissingPhoneNumber {
            get {
                return ResourceManager.GetString("Contacts_Error_MissingPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string ContactsViewModel_ContactsTypeOption_Company {
            get {
                return ResourceManager.GetString("ContactsViewModel_ContactsTypeOption_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not Specified).
        /// </summary>
        internal static string ContactsViewModel_ContactsTypeOption_NotSpecified {
            get {
                return ResourceManager.GetString("ContactsViewModel_ContactsTypeOption_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string ContactsViewModel_ContactsTypeOption_Person {
            get {
                return ResourceManager.GetString("ContactsViewModel_ContactsTypeOption_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts type must be selected.
        /// </summary>
        internal static string ContactsViewModel_Error_MissingContactsType {
            get {
                return ResourceManager.GetString("ContactsViewModel_Error_MissingContactsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contacts.
        /// </summary>
        internal static string ContactViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ContactViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save an invalid Contacts..
        /// </summary>
        internal static string ContactViewModel_Exception_CannotSave {
            get {
                return ResourceManager.GetString("ContactViewModel_Exception_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot search.
        /// </summary>
        internal static string ContactViewModel_Exception_CannotSearch {
            get {
                return ResourceManager.GetString("ContactViewModel_Exception_CannotSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contact.
        /// </summary>
        internal static string MainWindowViewModel_Command_CreateNewContacts {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_CreateNewContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Contacts.
        /// </summary>
        internal static string MainWindowViewModel_Command_SearchAllContacts {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_SearchAllContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Contacts.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllContacts {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Personal Phone Manager.
        /// </summary>
        internal static string MainWindowViewModel_DisplayName {
            get {
                return ResourceManager.GetString("MainWindowViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Contacts.
        /// </summary>
        internal static string SearchContactsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("SearchContactsViewModel_DisplayName", resourceCulture);
            }
        }
    }
}
